# @package _global_

defaults:
  - /habitat_baselines: imagenav_habitat_baselines_config_base
  - /benchmark@: imagenav
  - _self_

habitat:
  task:
    success_reward: 2.5
    slack_reward: -1e-3
  
  simulator:
    rearrange_sim_close_threshold: 128
    rearrange_sim_destroy_flag: False
    scenes_recompute_navmesh: ["data/hssd-hab/scenes-uncluttered/105515301_173104305.scene_instance.json"]
    recompute_navmesh_temp_dir: "dataset/temp_recomputed_navmesh"

habitat_baselines:
  verbose: False
  trainer_name: "ddppo"
  torch_gpu_id: 0
  tensorboard_dir: "${hydra:sweep.dir}/logs"
  video_dir: "${hydra:sweep.dir}/video"
  test_episode_count: -1
  eval_ckpt_path_dir: "${hydra:sweep.dir}/checkpoints"
  num_environments: 8 #20
  checkpoint_folder: "${hydra:sweep.dir}/checkpoints"
  num_updates: -1
  total_num_steps: 500e6
  log_interval: 1
  num_checkpoints: 20
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True
  updater_name: "ImageNavPPO"
  distrib_updater_name: "ImageNavDDPPO"

  # eval:
  #   split: "val_combined"

  rl:
    policy:
      main_agent:
        name: "ImageNavPolicy"
        rnn_type: "LSTM"
        num_recurrent_layers: 2
        use_augmentations: True
        use_augmentations_test_time: True
        normalize_visual_inputs: False
        freeze_backbone: False

    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      encoder_lr: 1.5e-6
      wd: 1e-6
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 64
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50

      use_normalized_advantage: False

      hidden_size: 512

      # Use double buffered sampling, typically helps
      # when environment time is similar or larger than
      # policy inference time during rollout generation
      use_double_buffered_sampler: False
    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: True

      # Model parameters
      backbone: resnet50
      rnn_type: LSTM
      num_recurrent_layers: 2