# @package _global_

defaults:
  - /habitat: habitat_config_base

  - /simulator@habitat.simulator: findingdory_sim
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgb_head_agent
  - /agents@habitat.simulator.agents.main_agent: stretch_rgb
  - /task@habitat.task: imagenav
  - /dataset@habitat.dataset: findingdory_hssd
  - _self_

habitat:
  env_task: GymImageNavEnv
  gym:
    obs_keys:
      - head_rgb
      - imagegoal_rotation
  environment:
    max_episode_steps: 1000
    iterator_options:
      max_scene_repeat_steps: 50000
  simulator:
    forward_step_size: 0.25
    turn_angle: 10
